# Generated by Django 3.0.3 on 2020-03-02 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('moisture', models.FloatField()),
                ('battery', models.FloatField()),
                ('panel', models.FloatField()),
                ('com_status', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tx_frec', models.IntegerField()),
                ('tx_slot', models.IntegerField()),
                ('rx_window', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('flow', models.FloatField()),
                ('battery', models.FloatField()),
                ('panel', models.FloatField()),
                ('com_status', models.BooleanField()),
                ('valve_status', models.BooleanField()),
                ('tot_flow', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('tx_frec', models.IntegerField()),
                ('tx_slot', models.IntegerField()),
                ('rx_window', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValveData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.FloatField()),
                ('battery', models.FloatField()),
                ('panel', models.FloatField()),
                ('valve_status', models.BooleanField()),
                ('update', models.DateTimeField()),
                ('valve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Valve')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture', models.FloatField()),
                ('battery', models.FloatField()),
                ('panel', models.FloatField()),
                ('update', models.DateTimeField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodes.Sensor')),
            ],
        ),
    ]
