# Generated by Django 3.0.3 on 2020-03-03 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_up',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='battery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='com_status',
            field=models.BooleanField(default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='latitude',
            field=models.FloatField(default=-13.489983),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='longitude',
            field=models.FloatField(default=-72.457463),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='moisture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='panel',
            field=models.FloatField(default=0, verbose_name='Solar Panel'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='rx_window',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tx_frec',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tx_slot',
            field=models.IntegerField(default=5),
        ),
    ]
