# Generated by Django 3.0.3 on 2020-03-03 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20200303_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='last_up',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='battery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='moisture',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='panel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='valve',
            name='battery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valve',
            name='com_status',
            field=models.BooleanField(default=False, verbose_name='Communication Status'),
        ),
        migrations.AlterField(
            model_name='valve',
            name='flow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valve',
            name='latitude',
            field=models.FloatField(default=-13.489983),
        ),
        migrations.AlterField(
            model_name='valve',
            name='longitude',
            field=models.FloatField(default=-72.457463),
        ),
        migrations.AlterField(
            model_name='valve',
            name='panel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valve',
            name='rx_window',
            field=models.IntegerField(verbose_name=10),
        ),
        migrations.AlterField(
            model_name='valve',
            name='tot_flow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valve',
            name='tx_frec',
            field=models.IntegerField(verbose_name=60),
        ),
        migrations.AlterField(
            model_name='valve',
            name='tx_slot',
            field=models.IntegerField(verbose_name=5),
        ),
        migrations.AlterField(
            model_name='valve',
            name='valve_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='valvedata',
            name='battery',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valvedata',
            name='flow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valvedata',
            name='panel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='valvedata',
            name='update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Update'),
        ),
        migrations.AlterField(
            model_name='valvedata',
            name='valve_status',
            field=models.BooleanField(default=False),
        ),
    ]
