# Generated by Django 3.0.3 on 2020-03-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20200303_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='valve_command',
            field=models.BooleanField(default=False, verbose_name='Valve Command'),
        ),
        migrations.AlterField(
            model_name='valve',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='valve',
            name='valve_status',
            field=models.BooleanField(default=False, verbose_name='Valve Status'),
        ),
    ]
